name: Release » Process release tag

on:
  workflow_dispatch:
  push:
    tags:
      # CF: 17.x-YYYY-MM-DD
      - '*.x-*-*-*'

jobs:
  build-release-tarballs:
    name: Create release from tag
    if: github.repository_owner == 'Arnei'
    runs-on: ubuntu-latest
    outputs:
      checksum: ${{ steps.tarball.outputs.checksum }}
      tag: ${{ steps.tarball.outputs.tag }}
      branch: ${{ steps.tarball.outputs.branch }}
    permissions:
      contents: write #for the release
      pull-requests: write #For the PR in the upstream repo

    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Get Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Run npm ci
        run: npm ci

      - name: Build the app
        env:
          PUBLIC_URL: /editor-ui
          VITE_APP_SETTINGS_PATH: /ui/config/editor/editor-settings.toml
        run: npm run build

      - name: Create release tarball
        id: tarball
        working-directory: build
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tar -czf "../oc-editor-$(git describe --tags).tar.gz" *
          echo checksum=`sha256sum ../oc-editor-$(git describe --tags).tar.gz | cut -f 1 -d " "` >> $GITHUB_OUTPUT
          echo tag=$(git describe --tags) >> $GITHUB_OUTPUT
          while read branchname
          do
            LAST_BRANCH="$branchname"
            #branchname looks like 'r/17.x', the describe + cut looks like '17.x', so we prefix with r/
            # NB: branchname == develop is not handled here, it's handled below
            if [ "$branchname" != "r/`git describe --tags | cut -f 1 -d -`" ]; then
              continue
            fi
            echo "Base branch is $branchname"
            BASE_BRANCH="$branchname"
            echo "branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
            break
          done <<< `gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository_owner }}/opencast/branches?per_page=100 | \
            jq -r '. | map(select(.name | match("r/[0-9]*.x"))) | .[].name'`
          #Figure out what develop branch's version should be
          # Bash is, without a doubt, the worst possible way to do this, but here we are...
          export DEVELOP_VERSION=$(($(echo $LAST_BRANCH | cut -f 2 -d '/' | cut -f 1 -d '.') + 1)).x
          #If we didn't find a match above, *and* the develop branch matches the tag
          if [ -z "${BASE_BRANCH}" -a "$DEVELOP_VERSION" == "`git describe --tags | cut -f 1 -d -`" ]; then
            echo "Base branch is develop, version $DEVELOP_VERSION"
            # Develop is by definition (LAST_BRANCH + 1).x
            echo "branch=develop" >> $GITHUB_OUTPUT
          fi

      - name: Create new release in github
        uses: softprops/action-gh-release@v2
        with:
          files: oc-editor-*.tar.gz
          fail_on_unmatched_files: true
          generate_release_notes: true
